module.exports = [
  'social media',
  'social media marketing',
  'data science',
  'predictive analytics',
  'big data',
  'Facebook',
  'Twitter',
  'market research',
  'survey research',
  'crm',
  'customer relationship management', 
  'branding', 
  'brand development', 
  'text messaging', 
  'sms marketing', 
  'geolocation', 
  'Instagram', 
  'Youtube', 
  'higher education', 
  'higher education marketing', 
  'enrollment marketing', 
  'admissions marketing', 
  'college admissions', 
  'conversational UI', 
  'conversational UX', 
  'conversational user interface', 
  'quantitative research', 
  'qualitative research', 
  'marketing metrics', 
  'marketing analytics', 
  'social media monitoring', 
  'smm', 
  'social media listening', 
  'brand monitoring', 
  'website', 
  'cms', 
  'mobile', 
  'iphone', 
  'android', 
  'marketing software', 
  'marketing technology' 
];
